### ISSUE TITLE
How do I alter the theme for custom transparency and blur?

### ISSUE THREAD

**Issue by Simbaclaws** [vanRooijen/dot_files#3]
Hi there,

I'm currently using your dot files because I think this is a great rice and looks amazing.

However, I'm trying to make all my windows slightly transparent with a blur effect behind it. But whatever I change in the gtk css files, don't seem to get applied in the theme...

I tried setting the:
- theme_bg_color
- window_bg_color

But changing it to anything else doesn't seem to do anything.

Can you perhaps give me any pointers on where I should start?

Is there some sort of compilation I have to do in order to get the css to work?

**Comment by vanRooijen** [comment]
Apologies for the late reply,

I did not add the blur effect with CSS, (I don't think such styling is supported natively by Mutter), I simply used a gnome extension called Blur my Shell.
There is a specific "Application blur" setting, which is very customizable and sufficient for my purposes.

It is a beta function, so it should be mentioned it might have some problems, however I have not experienced much issues.

What I love especially about this extension is you can whitelist / blacklist applications for blurring so I can set the application that I find either have problems or I don't want blurred on the blacklist. (like when watching videos I don't want transparency)

Hope this helps in terms of blurring and transparency.

With regards to the compilation of CSS, you can not compile CSS it must just be reloaded.
In this case you simply have to restart your gnome session, this can be done by logging out and back in.
However if you are using X11 you can simply press Alt + F2 and then just run "r".
This will automatically restart the gnome session, which will reload your CSS and is much faster.
